### ISSUE TITLE
Error example chat.php

### ISSUE THREAD

**Issue by martingerlero** [maximerenou/php-bing-ai#16] opened 2023-11-23 11:49 UTC
Hello, I am trying to make the API work and I am not successful. After several failed attempts, I tried to run the chat example directly, replacing the cookie with the corresponding one, and it gives me the same error. Which is the following: 

“Warning: Undefined array key “conversationSignature” in /home/martinge/vendor/maximerenou/bing-ai/src/Chat/Conversation.php on line 43 
Type “q” to quit > 
Fatal error: Uncaught Error: Undefined constant “STDIN” in /home/martinge/holapy.com.ar/test.php:24 Stack trace: #0 {main} thrown in /home/martinge/holapy.com.ar/test.php on line 24”

Does anyone know how to solve it or have a working example, so I can work from there? Since I am not able to make it work.

Thank you.

**Comment by maximerenou** [comment] 2024-01-02 13:47
Duplicate of #15

**Closed as not planned by maximerenou** 2024-01-02 13:47 UTC
